language: node_js
node_js:
- 9.2.0
- 9.0.0
deploy:
  provider: npm
  email: dev@knowre.com
  api_key:
    secure: W7T2VPGFipDByLCoX3/qZo2aIsps27JzBdLTMZyAvmUWlTfld6xQ+PXRf+hF8hx1gyUBI7esDalfjQN5eT3G94xQRvR8WAOADe64SL0NOYZMi1uys7kY4ywclaG+UxkGpO2rA1ANXxiwaUGQZTAuFTXKpde5JeReyHPAo0Z5Gyj260OnpMmRb/vbOSXAy1QpX3PNyUJkr/z1FY4sO0MkvLxtGHpek7ZFpH1ICPB6QJkHLSzUMi5TzL/uSCNFc1jt2xtrQoyktU7vrNA1vGx7wmzb/s31KEt90zhAG6sDorjxpzAUY3P1zlNp6ju1PwR7eeNvw6Cy8Mvu3hGukBG0ZhSyVcUVHdqipGgLL3IwiuKHZ0NVlvchHs8h8P6FU0NxEOTQ1IqmLdTTeFlr6ITl6j75tTyNUgiygh1TWPfugmeZLXZcZlINxk1maVVHWt+HdSmjn15oVNWh68Y0g4R/zdft5O1CaSZz5yWbOLA/tOxxPfPh8sSd1WH8jLX8NMSSCT+hYbjGlckSXcjrZ4xyMoOJgemWshT1fIU8yrCD02JLjtole137p98V9osJQT3mNTEeaVdz3kfq2sOv+mu/5MZes74EiIG5LbwFCGrIOPUimypY3eOvpsQri5Pt/DYoJ/wuWam54iH+nF8AeQERoCj5kpUyQDqAikv8jxVS2Uc=
  on:
    branch: stable
    node_js: 9.2.0
notifications:
  slack:
    secure: rEdI39/+PAGPaLU+CPR6Ew39VdS9S9H44dsPJjYmiFV9HI+7lLCsI1E9xkR8awUBmfX3MhBjs/EFsB1GAjNklOAR9WRUAbKdlEzGIszepwUBYA10zV9nplMDOKCZA/19YpMdgfVYyLzC/7Jwfe496G1mRu+Nm90xXHvC4efYZI+79OZ9IohV5Y4+ZBsDUT75Vhiuo8DCk25jEvGjez1epZ4SOXNrANwnHfdQ8yqrndnX4hRG+WIb+A2d3oOOurCeZyXWdxQMugZ5O/pnWGw9bpmvpmReqrCQbfigwXHUVf9OOAzHs4lELfSVbEu5UU47xCzTfwvk+esSS/Rhmj6DmyDdIgtDsw4HrMJdDVG5AKBMy0TIlJNs87bLPAjYE6hsW7vFXsOwggZg8RGW34Co+xQP9LbizbPuvHAh04HOzem+1BC4EaVE0uVnEC5GHLRJ4NeW1n8aqPjC+MkTmeWN+Use/4Q2KAi/sSBACqZMzYaQCFh5wIT+mOE22gUQbB1hPKqfE0QrqOQZILuNxAjff5AD5kMd/CAoB+jExFvjk4aFmIqQa2HcHwHt50Etpz5GP45riWxKnzwADrv62isltDYpbBMLDuj//jyU2TfmXWAlAcB4uFBVFoSxBHPVYCT7RlJqfoGyS+XKXWesUDH1JcrWCfdwcCpvvK5ZneaQwXY=
env:
  global:
    secure: 0gvAjv0KznmckvCNocEVcPAqXI57P3yw3LhyZPd8gDvHc2w/D6ln+jqp3KAXa3QMnnJY4wsMaPrenZrV0IERTSKRgV5RTVcWecid1pIJEMAqFOyoPJNkqE7QLrl+WYOATP1hhS5zrgRoNd1S0kBOMAPw23sH+4d3ajRVsP3DkOiupD/YxvOLCMM0T7A4kbmz86KRaIzqLowXAP62kjM2pZxYyBBw2dbiPtq6P0fOZ2rLSbEiQwDU+a0llSJh9u3d0pfArPlN8MmTL3l2Lol+9n6gE1mkfSIe4fAKuu+l1JRT1miW21Xy+xYZo3IGtxhh8xuUpsaJNFo/ZKJR/JZBUwczlbyIziNaLzZNBKtj2qAEM2vakb/GOny0TvgPNtdE8fOfQCPMUjiHfcYMYjFuOR7GwMAw63XS5+Fa5dGYbFrdKNwAW2VPIgZrYgjEmcKV0uBZOad7PVSk12pzcuVrbCPHN/wmvwtXaw6W9AtGSDIaZlrsLdeWu2dvvwASPMVk8c07RMMqHlifGZpUGBgEHMKPMbfM9tZGe0/pvmgw1UaRmDDq8I5vFxUxAiK+l9aSd2+WZHKoVaRmcAcfPDCnRr97arE86lo0vuZ/thaukvYzoHI1oN9Tez4cqJ4c8aNAOTDX8IdROft3vHJcjHBjuT5ra8+jG9W8AwI/V7d1X80=
